#!/bin/zsh
export PYTHONPATH=../../
RED="\e[00;31m"
NO_COLOR="\e[00m"
function e(){
	echo $RED$1$NO_COLOR
}

########################## quick sort is the benchmark #############

e "quick sort sorted array:" 
for (( i=0 ;i<3 ;i++ )) time python quick_sort.py 1000000 true
e "quick sort unsorted array:"
for (( i=0 ;i<3 ;i++ )) time python quick_sort.py 1000000 false

########################## OTHERS ###########################

e "kway merge sort sorted array:" 
for (( i=0 ;i<3 ;i++ )) time python ./kway_mergesort.py 1000000 true
e "kway merge sort unsorted array:"
for (( i=0 ;i<3 ;i++ )) time python ./kway_mergesort.py 1000000 false


e "quick sort functional sorted array:" 
for (( i=0 ;i<3 ;i++ )) time python quick_sort_functional.py 1000000 true
e "quick sort functional unsorted array:"
for (( i=0 ;i<3 ;i++ )) time python quick_sort_functional.py 1000000 false

e "OO heap sort sorted array:" 
for (( i=0 ;i<3 ;i++ )) time python ../../ds/heap.py 1000000 true
e "OO heap sort unsorted array:"
for (( i=0 ;i<3 ;i++ )) time python ../../ds/heap.py 1000000 false

e "heap sort sorted array:" 
for (( i=0 ;i<3 ;i++ )) time python heap_sort.py 1000000 true
e "heap sort unsorted array:"
for (( i=0 ;i<3 ;i++ )) time python heap_sort.py 1000000 false

e "merge sort sorted array:"
for (( i=0 ;i<3 ;i++ )) time python merge_sort.py 1000000 true
e "merge sort un sorted array:"
for (( i=0 ;i<3 ;i++ )) time python merge_sort.py 1000000 false

e "selection sort sorted array:"
for (( i=0 ;i<3 ;i++ )) time python selection_sort.py 1000000 true

e "counting sort sorted array:"
for (( i=0 ;i<3 ;i++ )) time python counting_sort.py 1000000 true
e "counting sort un sorted array:"
for (( i=0 ;i<3 ;i++ )) time python counting_sort.py 1000000 false

