//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.3705.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.0.3705.0.
// 
namespace RND.com.teachatechie {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TextToImageSoap", Namespace="http://teachatechie.com/")]
    public class TextToImage : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public TextToImage() {
            this.Url = "http://teachatechie.com/GJTTVBWebServices/TextToImage.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://teachatechie.com/LoadSettings", RequestNamespace="http://teachatechie.com/", ResponseNamespace="http://teachatechie.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet LoadSettings() {
            object[] results = this.Invoke("LoadSettings", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginLoadSettings(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("LoadSettings", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndLoadSettings(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://teachatechie.com/LoadColors", RequestNamespace="http://teachatechie.com/", ResponseNamespace="http://teachatechie.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] LoadColors() {
            object[] results = this.Invoke("LoadColors", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginLoadColors(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("LoadColors", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndLoadColors(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://teachatechie.com/LoadFontFamily", RequestNamespace="http://teachatechie.com/", ResponseNamespace="http://teachatechie.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] LoadFontFamily() {
            object[] results = this.Invoke("LoadFontFamily", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginLoadFontFamily(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("LoadFontFamily", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndLoadFontFamily(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://teachatechie.com/LoadFontStyles", RequestNamespace="http://teachatechie.com/", ResponseNamespace="http://teachatechie.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] LoadFontStyles() {
            object[] results = this.Invoke("LoadFontStyles", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginLoadFontStyles(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("LoadFontStyles", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndLoadFontStyles(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://teachatechie.com/LoadFontSizes", RequestNamespace="http://teachatechie.com/", ResponseNamespace="http://teachatechie.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] LoadFontSizes() {
            object[] results = this.Invoke("LoadFontSizes", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginLoadFontSizes(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("LoadFontSizes", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndLoadFontSizes(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://teachatechie.com/RenderText", RequestNamespace="http://teachatechie.com/", ResponseNamespace="http://teachatechie.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RenderText(string FontStyle, string FontSize, string FontFamily, string ImageText, string BackgroundColor, string ForegroundColor) {
            object[] results = this.Invoke("RenderText", new object[] {
                        FontStyle,
                        FontSize,
                        FontFamily,
                        ImageText,
                        BackgroundColor,
                        ForegroundColor});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginRenderText(string FontStyle, string FontSize, string FontFamily, string ImageText, string BackgroundColor, string ForegroundColor, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("RenderText", new object[] {
                        FontStyle,
                        FontSize,
                        FontFamily,
                        ImageText,
                        BackgroundColor,
                        ForegroundColor}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndRenderText(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
}
