//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.3705.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=1.0.3705.0.
// 
using System.Diagnostics;
using System.Xml.Serialization;
using System;
using System.Web.Services.Protocols;
using System.ComponentModel;
using System.Web.Services;


/// <remarks/>
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="DailyHoroSoap", Namespace="http://tempuri.org/")]
public class DailyHoro : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    /// <remarks/>
    public DailyHoro() {
        this.Url = "http://www.dev1.eraserver.net/nakul/wshoro.asmx";
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetHoro", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string GetHoro(string zodiac) {
        object[] results = this.Invoke("GetHoro", new object[] {
                    zodiac});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetHoro(string zodiac, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetHoro", new object[] {
                    zodiac}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndGetHoro(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
}
